import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${robotoMono.variable} ${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <NavBar />
        <div className="relative overflow-hidden">
          <div className="absolute w-full h-full bottom-0 translate-y-9/12  bg-radial from-white/10 to-50% to-transparent scale-200 pointer-events-none" />
          {children}
        </div>
      </body>
    </html>
  );
}
